repository: hhttps://github.com/iROCKBUNNY/WMIS-Demo

timezone: Asia/Shanghai
lang: zh_CN

name: WMIS Demo
author: iROCKBUNNY
author_url: http://irockbunny.com
organization: TEELAB
organization_url: http://teelab.net
description: Warehouse Management Information System (Demo)
url: http://wmis.creamcxx.com
contact: c@creamcxx.com

logo: /apple-touch-icon.png

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor