repository: https://github.com/CreamCXX/WMIS-Demo

timezone: Asia/Shanghai
lang: zh_CN

title: WMIS Demo
description: Warehouse Management Information System (Demo)
url: https://wmis.creamcxx.com

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net

contact: c@creamcxx.com

image: /apple-touch-icon.png
logo: /apple-touch-icon.png

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor